CLI: Password Class Reference
Password Class Reference
Password user interface object.
#include <ui_password.h>
Public Member Functions
Password (const bool B_DisplayStars, const int I_MinPasswordLength, const int I_MaxPasswordLength)
Top execution context constructor.
Password (ExecutionContext &CLI_ParentContext, const bool B_DisplayStars, const int I_MinPasswordLength, const int I_MaxPasswordLength)
Child execution context constructor.
virtual ~Password (void)
Destructor.
const tk::String GetPassword (void) const
Password retrieval.
virtual void OnKey (const KEY E_KeyCode)
Handler called on character input.
Public Member Functions inherited from UI
virtual ~UI (void)
Destructor.
const bool GetbExecResult (void) const
Execution result accessor.
Public Member Functions inherited from ExecutionContext
virtual ~ExecutionContext (void)
Destructor.
ExecutionContextManager & GetContextManager (void)
Execution context manager accessor.
const IODevice & GetInput (void) const
Input stream accessor.
const OutputDevice & GetStream (const STREAM_TYPE E_StreamType) const
Output stream accessor.
const bool SetStream (const STREAM_TYPE E_StreamType, OutputDevice &CLI_Stream)
Output stream positionning.
const bool StreamEnabled (const STREAM_TYPE E_StreamType) const
Enabled/disabled stream accessor.
const bool EnableStream (const STREAM_TYPE E_StreamType, const bool B_Enable)
Enable/disable stream.
void SetLang (const ResourceString::LANG E_Lang)
Language setting.
const ResourceString::LANG GetLang (void) const
Language access.
void SetBeep (const bool B_Enable)
Beep configuration setting.
const bool GetBeep (void) const
Beep configuration access.
void Beep (void)
Sends a beep signal.
void Run (IODevice &CLI_IODevice)
Runs the execution context onto the corresponding input/output device.
void Run (void)
Runs the execution context as a child context of the parent given by the construction.
const bool IsRunning (void) const
Tells whether this execution context is running or not.
void StopExecution (void)
Terminates this execution context's execution.
void StopAllExecutions (void)
Terminates execution for all execution contexts attached to the same top execution context.
Public Member Functions inherited from Object
virtual ~Object (void)=0
Pure virtual destructor.
Protected Member Functions
virtual void Reset (void)
Handler called when data reset is required.
virtual void ResetToDefault (void)
Handler called when default value is required to be restored.
Protected Member Functions inherited from UI
UI (void)
Top execution context constructor.
UI (ExecutionContext &CLI_ExecutionContext)
Child execution context constructor.
virtual const bool OnStartExecution (void)
Beginning of execution handler.
virtual const bool OnStopExecution (void)
Execution termination handler.
void EndControl (const bool B_ExecResult)
Method to call by child classes in order to end the control execution.
Protected Member Functions inherited from ExecutionContext
ExecutionContext (void)
Top context constructor.
ExecutionContext (ExecutionContext &CLI_ParentContext)
Child context constructor.
Protected Member Functions inherited from Object
Object (void)
Default constructor only available to sub-classes.
Detailed Description
Password user interface object.
Definition at line 47 of file ui_password.h.
Constructor & Destructor Documentation
Password() [1/2]
Password::Password (const bool B_DisplayStars, const int I_MinPasswordLength, const int I_MaxPasswordLength) explicit
Top execution context constructor.
Parameters
B_DisplayStars true in order to display '*' for each character, false for no display at all.
I_MinPasswordLength Minimum password length required. -1 if not set.
I_MaxPasswordLength Maximum password length required. -1 if not set.
Definition at line 39 of file ui_password.cpp.
Referenced by Password().
Password() [2/2]
Password::Password (ExecutionContext & CLI_ParentContext, const bool B_DisplayStars, const int I_MinPasswordLength, const int I_MaxPasswordLength) explicit
Child execution context constructor.
Parameters
CLI_ParentContext Parent execution context.
B_DisplayStars true in order to display '*' for each character, false for no display at all.
I_MinPasswordLength Minimum password length required. -1 if not set.
I_MaxPasswordLength Maximum password length required. -1 if not set.
Definition at line 46 of file ui_password.cpp.
References Password().
~Password()
Password::~Password (void) virtual
Destructor.
Definition at line 53 of file ui_password.cpp.
Member Function Documentation
GetPassword()
const tk::String Password::GetPassword (void) const
Password retrieval.
Returns
Password entered by the user.
Definition at line 59 of file ui_password.cpp.
References CmdLineEdition::GetLine().
OnKey()
void Password::OnKey (const KEY E_KeyCode) virtual
Handler called on character input.
Parameters
E_KeyCode Input key.
Implements ExecutionContext.
Definition at line 78 of file ui_password.cpp.
References BACKSPACE, ExecutionContext::Beep(), BREAK, CmdLineEdition::CleanAll(), CLS, DELETE, CmdLineEdition::Delete(), ECHO_STREAM, CmdLineEdition::End(), UI::EndControl(), ENTER, ESCAPE, CmdLineEdition::GetLeft(), CmdLineEdition::GetLine(), OutputDevice::GetNullDevice(), CmdLineEdition::GetRight(), ExecutionContext::GetStream(), CmdLineEdition::Home(), KEY_BEGIN, KEY_END, KEY_LEFT, KEY_RIGHT, LOGOUT, CmdLineEdition::MoveCursor(), CmdLineEdition::NextLine(), NULL_KEY, CmdLineEdition::Reset(), and TAB.
Reset()
void Password::Reset (void) protected virtual
Handler called when data reset is required.
Implements UI.
Definition at line 64 of file ui_password.cpp.
References CmdLineEdition::Reset().
ResetToDefault()
void Password::ResetToDefault (void) protected virtual
Handler called when default value is required to be restored.
Implements UI.
Definition at line 70 of file ui_password.cpp.
References CmdLineEdition::CleanAll(), ECHO_STREAM, ExecutionContext::GetStream(), and CmdLineEdition::Reset().
The documentation for this class was generated from the following files:
ui_password.h
ui_password.cpp