CLI: Less Class Reference
Less Class Reference
Simple line user interface object.
#include <ui_less.h>
Public Member Functions
Less (const unsigned int UI_MaxLines, const unsigned int UI_MaxLineLength)
Top execution context constructor.
Less (ExecutionContext &CLI_ParentContext, const unsigned int UI_MaxLines, const unsigned int UI_MaxLineLength)
Child execution context constructor.
virtual ~Less (void)
Destructor.
const OutputDevice & GetText (void)
Text member accessor.
virtual void OnKey (const KEY E_KeyCode)
Handler called on character input.
Public Member Functions inherited from UI
virtual ~UI (void)
Destructor.
const bool GetbExecResult (void) const
Execution result accessor.
Public Member Functions inherited from ExecutionContext
virtual ~ExecutionContext (void)
Destructor.
ExecutionContextManager & GetContextManager (void)
Execution context manager accessor.
const IODevice & GetInput (void) const
Input stream accessor.
const OutputDevice & GetStream (const STREAM_TYPE E_StreamType) const
Output stream accessor.
const bool SetStream (const STREAM_TYPE E_StreamType, OutputDevice &CLI_Stream)
Output stream positionning.
const bool StreamEnabled (const STREAM_TYPE E_StreamType) const
Enabled/disabled stream accessor.
const bool EnableStream (const STREAM_TYPE E_StreamType, const bool B_Enable)
Enable/disable stream.
void SetLang (const ResourceString::LANG E_Lang)
Language setting.
const ResourceString::LANG GetLang (void) const
Language access.
void SetBeep (const bool B_Enable)
Beep configuration setting.
const bool GetBeep (void) const
Beep configuration access.
void Beep (void)
Sends a beep signal.
void Run (IODevice &CLI_IODevice)
Runs the execution context onto the corresponding input/output device.
void Run (void)
Runs the execution context as a child context of the parent given by the construction.
const bool IsRunning (void) const
Tells whether this execution context is running or not.
void StopExecution (void)
Terminates this execution context's execution.
void StopAllExecutions (void)
Terminates execution for all execution contexts attached to the same top execution context.
Public Member Functions inherited from Object
virtual ~Object (void)=0
Pure virtual destructor.
Protected Member Functions
virtual void Reset (void)
Handler called when data reset is required.
virtual void ResetToDefault (void)
Handler called when default value is required to be restored.
Protected Member Functions inherited from UI
UI (void)
Top execution context constructor.
UI (ExecutionContext &CLI_ExecutionContext)
Child execution context constructor.
virtual const bool OnStartExecution (void)
Beginning of execution handler.
virtual const bool OnStopExecution (void)
Execution termination handler.
void EndControl (const bool B_ExecResult)
Method to call by child classes in order to end the control execution.
Protected Member Functions inherited from ExecutionContext
ExecutionContext (void)
Top context constructor.
ExecutionContext (ExecutionContext &CLI_ParentContext)
Child context constructor.
Protected Member Functions inherited from Object
Object (void)
Default constructor only available to sub-classes.
Detailed Description
Simple line user interface object.
Definition at line 52 of file ui_less.h.
Constructor & Destructor Documentation
Less() [1/2]
Less::Less (const unsigned int UI_MaxLines, const unsigned int UI_MaxLineLength) explicit
Top execution context constructor.
Parameters
UI_MaxLines Maximum number of lines
UI_MaxLineLength Maximum length of lines
Definition at line 42 of file ui_less.cpp.
Referenced by Less().
Less() [2/2]
Less::Less (ExecutionContext & CLI_ParentContext, const unsigned int UI_MaxLines, const unsigned int UI_MaxLineLength) explicit
Child execution context constructor.
Parameters
CLI_ParentContext Parent execution context.
UI_MaxLines Maximum number of lines
UI_MaxLineLength Maximum length of lines
Definition at line 49 of file ui_less.cpp.
References Less().
~Less()
Less::~Less (void) virtual
Destructor.
Definition at line 56 of file ui_less.cpp.
Member Function Documentation
GetText()
const OutputDevice & Less::GetText (void)
Text member accessor.
Returns
Text member reference.
Definition at line 67 of file ui_less.cpp.
OnKey()
void Less::OnKey (const KEY E_KeyCode) virtual
Handler called on character input.
Parameters
E_KeyCode Input key.
Implements ExecutionContext.
Definition at line 90 of file ui_less.cpp.
References ExecutionContext::Beep(), Text::Begin(), CLI_ASSERT, Text::End(), ENTER, KEY_BEGIN, KEY_DOWN, KEY_END, KEY_UP, Text::LineDown(), Text::LineUp(), PAGE_DOWN, PAGE_UP, Text::PageDown(), Text::PageUp(), and SPACE.
Reset()
void Less::Reset (void) protected virtual
Handler called when data reset is required.
Implements UI.
Definition at line 72 of file ui_less.cpp.
ResetToDefault()
void Less::ResetToDefault (void) protected virtual
Handler called when default value is required to be restored.
Implements UI.
Definition at line 77 of file ui_less.cpp.
References Text::Begin(), CLI_ASSERT, OutputDevice::ScreenInfo::GetSafeHeight(), OutputDevice::GetScreenInfo(), ExecutionContext::GetStream(), and OUTPUT_STREAM.
The documentation for this class was generated from the following files:
ui_less.h
ui_less.cpp