CLI: OutputDevice Class Reference
OutputDevice Class Reference abstract
Generic output device.
#include <io_device.h>
Classes
class ScreenInfo
Screen information.
Public Member Functions
const tk::String GetDebugName (void) const
Debug name accessor.
const int UseInstance (const CallInfo &CLI_CallInfo)
Ensures instance validity.
const int FreeInstance (const CallInfo &CLI_CallInfo)
Releases the instance.
const int GetInstanceUsers (void) const
Instance user count accessor.
const bool OpenUp (const CallInfo &CLI_CallInfo)
Checks the device is opened.
const bool CloseDown (const CallInfo &CLI_CallInfo)
Indicates the device the client does not need the device to opened anymore.
const int GetOpenUsers (void) const
Open state user count accessor.
const OutputDevice & operator<< (const std::string &STR_Out) const
Output operator.
const OutputDevice & operator<< (const tk::String &STR_Out) const
Output operator.
const OutputDevice & operator<< (const char *const STR_Out) const
Output operator.
const OutputDevice & operator<< (const char C_Out) const
Output operator.
const OutputDevice & operator<< (const KEY E_Key) const
Output operator.
const OutputDevice & operator<< (const uint8_t UI8_Out) const
Output operator.
const OutputDevice & operator<< (const int16_t I16_Out) const
Output operator.
const OutputDevice & operator<< (const uint16_t UI16_Out) const
Output operator.
const OutputDevice & operator<< (const int32_t I32_Out) const
Output operator.
const OutputDevice & operator<< (const uint32_t UI32_Out) const
Output operator.
const OutputDevice & operator<< (const int64_t I64_Out) const
Output operator.
const OutputDevice & operator<< (const uint64_t UI64_Out) const
Output operator.
const OutputDevice & operator<< (const float F_Out) const
Output operator.
const OutputDevice & operator<< (const double D_Out) const
Output operator.
const OutputDevice & operator<< (const void *const PV_Out) const
Output operator.
const OutputDevice & operator<< (const IOEndl &CLI_IOEndl) const
Output operator.
const ResourceString GetLastError (void) const
Last error accessor.
virtual void PutString (const char *const STR_Out) const =0
Output handler.
virtual void Beep (void) const
Beep handler.
virtual void CleanScreen (void) const
Clean screen.
virtual const ScreenInfo GetScreenInfo (void) const
Screen info accessor.
virtual const bool WouldOutput (const OutputDevice &CLI_Device) const
Stack overflow protection.
Public Member Functions inherited from Object
virtual ~Object (void)=0
Pure virtual destructor.
Static Public Member Functions
static OutputDevice & GetNullDevice (void)
Null device singleton.
static OutputDevice & GetStdOut (void)
Standard output device singleton.
static OutputDevice & GetStdErr (void)
Standard error device singleton.
Protected Member Functions
OutputDevice (const char *const STR_DbgName, const bool B_AutoDelete)
Constructor.
virtual ~OutputDevice (void)
Destructor.
virtual const bool OpenDevice (void)=0
Device opening handler.
virtual const bool CloseDevice (void)=0
Device closure handler.
Protected Member Functions inherited from Object
Object (void)
Default constructor only available to sub-classes.
Protected Attributes
ResourceString m_cliLastError
Detailed Description
Generic output device.
See also
endl
Definition at line 256 of file io_device.h.
Constructor & Destructor Documentation
OutputDevice()
OutputDevice::OutputDevice (const char *const STR_DbgName, const bool B_AutoDelete) explicit protected
Constructor.
Parameters
STR_DbgName Debug name. Useful for traces only.
B_AutoDelete Auto-deletion flag.
~OutputDevice()
virtual OutputDevice::~OutputDevice (void) protected virtual
Destructor.
Member Function Documentation
Beep()
virtual void OutputDevice::Beep (void) const virtual
Beep handler.
Reimplemented in TelnetConnection, OutputFileDevice, InputFileDevice, IOMux, SingleCommand, Console, Text, and StringDevice.
CleanScreen()
virtual void OutputDevice::CleanScreen (void) const virtual
Clean screen.
Reimplemented in TelnetConnection, InputFileDevice, IOMux, SingleCommand, Console, Text, and StringDevice.
CloseDevice()
virtual const bool OutputDevice::CloseDevice (void) protected pure virtual
Device closure handler.
Returns
true for success, false otherwise.
Note
Devices have to be prepared to be called several times through this method. They should do the closure once only (unless they have been opened between CloseDevice() calls), and indicate no failure thereafter.
Implemented in TelnetConnection, OutputFileDevice, InputFileDevice, IOMux, SingleCommand, StringDevice, Text, and Console.
CloseDown()
const bool OutputDevice::CloseDown (const CallInfo & CLI_CallInfo)
Indicates the device the client does not need the device to opened anymore.
Returns
true for success, false otherwise.
Releases the lock on the open state. When no more user need the device to be opened, it is closed straight forward.
Parameters
CLI_CallInfo Call information.
FreeInstance()
const int OutputDevice::FreeInstance (const CallInfo & CLI_CallInfo)
Releases the instance.
Returns
Total number of instance users after this call.
If the auto-deletion flag has been set during construction, the object is auto-deleted when the number of users reaches 0 on this call.
Parameters
CLI_CallInfo Call information.
GetDebugName()
const tk::String OutputDevice::GetDebugName (void) const
Debug name accessor.
Returns
Debug name.
GetInstanceUsers()
const int OutputDevice::GetInstanceUsers (void) const
Instance user count accessor.
Returns
Number of instance users.
GetLastError()
const ResourceString OutputDevice::GetLastError (void) const
Last error accessor.
Returns
Last error resource string.
GetNullDevice()
static OutputDevice& OutputDevice::GetNullDevice (void) static
Null device singleton.
Returns
Null device reference.
Referenced by Text::LineDown(), and Password::OnKey().
GetOpenUsers()
const int OutputDevice::GetOpenUsers (void) const
Open state user count accessor.
Returns
Number of users that have opened the device.
GetScreenInfo()
virtual const ScreenInfo OutputDevice::GetScreenInfo (void) const virtual
Screen info accessor.
Returns
Screen info with possible ScreenInfo::UNKNOWN values.
Reimplemented in Console.
Referenced by More::OnKey(), Less::ResetToDefault(), and More::ResetToDefault().
GetStdErr()
static OutputDevice& OutputDevice::GetStdErr (void) static
Standard error device singleton.
Returns
Standard error device reference.
GetStdOut()
static OutputDevice& OutputDevice::GetStdOut (void) static
Standard output device singleton.
Returns
Standard output device reference.
OpenDevice()
virtual const bool OutputDevice::OpenDevice (void) protected pure virtual
Device opening handler.
Returns
true for success, false otherwise.
Note
Devices have to be prepared to be called several times through this method. They should do the opening once only (unless they have been closed between OpendDevice() calls), and indicate no failure thereafter.
Implemented in TelnetConnection, OutputFileDevice, InputFileDevice, IOMux, SingleCommand, Text, StringDevice, and Console.
OpenUp()
const bool OutputDevice::OpenUp (const CallInfo & CLI_CallInfo)
Checks the device is opened.
Returns
true for success, false otherwise.
Opens the device if not already opened. Acquire a lock on the open state in any case.
Parameters
CLI_CallInfo Call information.
operator<<() [1/16]
const OutputDevice& OutputDevice::operator<< (const std::string & STR_Out) const
Output operator.
Returns
The output device itself.
Author
[contrib: Oleg Smolsky, 2010, based on CLI 2.5]
Parameters
STR_Out Output string object.
operator<<() [2/16]
const OutputDevice& OutputDevice::operator<< (const tk::String & STR_Out) const
Output operator.
Returns
The output device itself.
Parameters
STR_Out Output string object.
operator<<() [3/16]
const OutputDevice& OutputDevice::operator<< (const char *const STR_Out) const
Output operator.
Returns
The output device itself.
Parameters
STR_Out Output null terminated string.
operator<<() [4/16]
const OutputDevice& OutputDevice::operator<< (const char C_Out) const
Output operator.
Returns
The output device itself.
Parameters
C_Out Single character.
operator<<() [5/16]
const OutputDevice& OutputDevice::operator<< (const KEY E_Key) const
Output operator.
Returns
The output device itself.
Parameters
E_Key Single character as a KEY.
operator<<() [6/16]
const OutputDevice& OutputDevice::operator<< (const uint8_t UI8_Out) const
Output operator.
Returns
The output device itself.
Parameters
UI8_Out 8 bits unsigned integer number.
operator<<() [7/16]
const OutputDevice& OutputDevice::operator<< (const int16_t I16_Out) const
Output operator.
Returns
The output device itself.
Parameters
I16_Out 16 bits integer number.
operator<<() [8/16]
const OutputDevice& OutputDevice::operator<< (const uint16_t UI16_Out) const
Output operator.
Returns
The output device itself.
Parameters
UI16_Out 16 bits unsigned integer number.
operator<<() [9/16]
const OutputDevice& OutputDevice::operator<< (const int32_t I32_Out) const
Output operator.
Returns
The output device itself.
Parameters
I32_Out 32 bits integer number.
operator<<() [10/16]
const OutputDevice& OutputDevice::operator<< (const uint32_t UI32_Out) const
Output operator.
Returns
The output device itself.
Parameters
UI32_Out 32 bits unsigned integer number.
operator<<() [11/16]
const OutputDevice& OutputDevice::operator<< (const int64_t I64_Out) const
Output operator.
Returns
The output device itself.
Parameters
I64_Out 64 bits integer number.
operator<<() [12/16]
const OutputDevice& OutputDevice::operator<< (const uint64_t UI64_Out) const
Output operator.
Returns
The output device itself.
Parameters
UI64_Out 64 bits unsigned integer number.
operator<<() [13/16]
const OutputDevice& OutputDevice::operator<< (const float F_Out) const
Output operator.
Returns
The output device itself.
Parameters
F_Out Float number.
operator<<() [14/16]
const OutputDevice& OutputDevice::operator<< (const double D_Out) const
Output operator.
Returns
The output device itself.
Parameters
D_Out Double number.
operator<<() [15/16]
const OutputDevice& OutputDevice::operator<< (const void *const PV_Out) const
Output operator.
Returns
The output device itself.
Parameters
PV_Out Void address.
operator<<() [16/16]
const OutputDevice& OutputDevice::operator<< (const IOEndl & CLI_IOEndl) const
Output operator.
Returns
The output device itself.
Parameters
CLI_IOEndl Carriage return.
PutString()
virtual void OutputDevice::PutString (const char *const STR_Out) const pure virtual
Output handler.
Parameters
STR_Out Output string.
Implemented in TelnetConnection, OutputFileDevice, InputFileDevice, IOMux, SingleCommand, Console, Text, and StringDevice.
UseInstance()
const int OutputDevice::UseInstance (const CallInfo & CLI_CallInfo)
Ensures instance validity.
Returns
Total number of instance users after this call.
Parameters
CLI_CallInfo Call information.
WouldOutput()
virtual const bool OutputDevice::WouldOutput (const OutputDevice & CLI_Device) const virtual
Stack overflow protection.
Parameters
CLI_Device Other device that the callee device should check it would output characters to.
Returns
true if the callee device would redirect characters to the given device for output.
Determines whether the current device would output the given device in any way. Default implementation checks whether CLI_Device is the self device.
Reimplemented in InputFileDevice, IOMux, SingleCommand, and Text.
Referenced by Text::WouldOutput().
Member Data Documentation
m_cliLastError
ResourceString OutputDevice::m_cliLastError mutable protected
Last error.
Returns
N/A (doxygen warning)
Definition at line 575 of file io_device.h.
The documentation for this class was generated from the following file:
io_device.h