CLI: OutputDevice::ScreenInfo Class Reference
OutputDevice::ScreenInfo Class Reference
Screen information.
#include <io_device.h>
Public Types
enum _RegularValues { UNKNOWN = -1, DEFAULT_WIDTH = 80, DEFAULT_HEIGHT = 20 }
ScreenInfo regular values.
Public Member Functions
ScreenInfo (const int I_Width, const int I_Height, const bool B_TrueCls, const bool B_WrapLines)
Constructor.
ScreenInfo (const ScreenInfo &CLI_Info)
Copy constructor.
virtual ~ScreenInfo (void)
Destructor.
ScreenInfo & operator= (const ScreenInfo &CLI_ScreenInfo)
Assignment operator.
const int GetWidth (void) const
Screen width accessor.
const unsigned int GetSafeWidth (void) const
Safe screen width accessor.
const int GetHeight (void) const
Screen height accessor.
const unsigned int GetSafeHeight (void) const
Safe screen height accessor.
const bool GetbTrueCls (void) const
True CleanScreen() characteristic accessor.
const bool GetbWrapLines (void) const
Line wrapping characteristic accessor.
Public Member Functions inherited from Object
virtual ~Object (void)=0
Pure virtual destructor.
Additional Inherited Members
Protected Member Functions inherited from Object
Object (void)
Default constructor only available to sub-classes.
Detailed Description
Screen information.
Definition at line 461 of file io_device.h.
Member Enumeration Documentation
_RegularValues
enum OutputDevice::ScreenInfo::_RegularValues
ScreenInfo regular values.
Enumerator
UNKNOWN
Unknown value constant for either width or height.
DEFAULT_WIDTH
Default width constant.
DEFAULT_HEIGHT
Default height constant.
Definition at line 465 of file io_device.h.
Constructor & Destructor Documentation
ScreenInfo() [1/2]
OutputDevice::ScreenInfo::ScreenInfo (const int I_Width, const int I_Height, const bool B_TrueCls, const bool B_WrapLines) inline explicit
Constructor.
Parameters
I_Width Width of screen. Can be UNKNOWN.
I_Height Height of screen. Can be UNKNOWN.
B_TrueCls True when an efficient CleanScreen() operation is implemented.
B_WrapLines True when the line automatically goes down when the cursor reached the right end of the screen.
Definition at line 477 of file io_device.h.
ScreenInfo() [2/2]
OutputDevice::ScreenInfo::ScreenInfo (const ScreenInfo & CLI_Info) inline
Copy constructor.
Parameters
CLI_Info Dimension object to copy.
Definition at line 487 of file io_device.h.
~ScreenInfo()
virtual OutputDevice::ScreenInfo::~ScreenInfo (void) inline virtual
Destructor.
Definition at line 494 of file io_device.h.
Member Function Documentation
GetbTrueCls()
const bool OutputDevice::ScreenInfo::GetbTrueCls (void) const inline
True CleanScreen() characteristic accessor.
Returns
True CleanScreen() characteristic.
Definition at line 523 of file io_device.h.
GetbWrapLines()
const bool OutputDevice::ScreenInfo::GetbWrapLines (void) const inline
Line wrapping characteristic accessor.
Returns
Line wrapping characteristic.
Definition at line 526 of file io_device.h.
GetHeight()
const int OutputDevice::ScreenInfo::GetHeight (void) const inline
Screen height accessor.
Returns
Screen height if known, UNKNOWN otherwise.
Definition at line 517 of file io_device.h.
References UNKNOWN.
GetSafeHeight()
const unsigned int OutputDevice::ScreenInfo::GetSafeHeight (void) const inline
Safe screen height accessor.
Returns
Screen height if known, default value otherwise.
Definition at line 520 of file io_device.h.
References DEFAULT_HEIGHT.
Referenced by More::OnKey(), Less::ResetToDefault(), and More::ResetToDefault().
GetSafeWidth()
const unsigned int OutputDevice::ScreenInfo::GetSafeWidth (void) const inline
Safe screen width accessor.
Returns
Screen width if known, default value otherwise.
Definition at line 514 of file io_device.h.
References DEFAULT_WIDTH.
Referenced by Text::LineDown(), Text::LineUp(), More::OnKey(), and More::ResetToDefault().
GetWidth()
const int OutputDevice::ScreenInfo::GetWidth (void) const inline
Screen width accessor.
Returns
Screen width if known, UNKNOWN otherwise.
Definition at line 511 of file io_device.h.
References UNKNOWN.
operator=()
ScreenInfo& OutputDevice::ScreenInfo::operator= (const ScreenInfo & CLI_ScreenInfo) inline
Assignment operator.
Returns
Same ScreenInfo instance reference.
Parameters
CLI_ScreenInfo Screen information to copy.
Definition at line 498 of file io_device.h.
The documentation for this class was generated from the following file:
io_device.h