CLI: YesNo Class Reference
YesNo Class Reference
Yes/No question user interface object.
#include <ui_yesno.h>
Public Member Functions
YesNo (const bool B_DefaultAnswer)
Top execution context constructor.
YesNo (ExecutionContext &CLI_ParentContext, const bool B_DefaultAnswer)
Child execution context constructor.
virtual ~YesNo (void)
Destructor.
const bool GetYesNo (void) const
Yes/No answer retrieval.
virtual void OnKey (const KEY E_KeyCode)
Handler called on character input.
Public Member Functions inherited from Choice
Choice (const int I_DefaultChoice, const tk::Queue< ResourceString > &TK_Choices)
Top execution context constructor.
Choice (ExecutionContext &CLI_ParentContext, const int I_DefaultChoice, const tk::Queue< ResourceString > &TK_Choices)
Child execution context constructor.
virtual ~Choice (void)
Destructor.
const int GetChoice (void) const
Choice retrieval.
const ResourceString GetstrChoice (void) const
Choice retrieval in its string form.
Public Member Functions inherited from Line
Line (const tk::String &TK_DefaultLine, const int I_MinLineLength, const int I_MaxLineLength)
Top execution context constructor.
Line (ExecutionContext &CLI_ParentContext, const tk::String &TK_DefaultLine, const int I_MinLineLength, const int I_MaxLineLength)
Child execution context constructor.
virtual ~Line (void)
Destructor.
const tk::String GetLine (void) const
Line retrieval.
Public Member Functions inherited from UI
virtual ~UI (void)
Destructor.
const bool GetbExecResult (void) const
Execution result accessor.
Public Member Functions inherited from ExecutionContext
virtual ~ExecutionContext (void)
Destructor.
ExecutionContextManager & GetContextManager (void)
Execution context manager accessor.
const IODevice & GetInput (void) const
Input stream accessor.
const OutputDevice & GetStream (const STREAM_TYPE E_StreamType) const
Output stream accessor.
const bool SetStream (const STREAM_TYPE E_StreamType, OutputDevice &CLI_Stream)
Output stream positionning.
const bool StreamEnabled (const STREAM_TYPE E_StreamType) const
Enabled/disabled stream accessor.
const bool EnableStream (const STREAM_TYPE E_StreamType, const bool B_Enable)
Enable/disable stream.
void SetLang (const ResourceString::LANG E_Lang)
Language setting.
const ResourceString::LANG GetLang (void) const
Language access.
void SetBeep (const bool B_Enable)
Beep configuration setting.
const bool GetBeep (void) const
Beep configuration access.
void Beep (void)
Sends a beep signal.
void Run (IODevice &CLI_IODevice)
Runs the execution context onto the corresponding input/output device.
void Run (void)
Runs the execution context as a child context of the parent given by the construction.
const bool IsRunning (void) const
Tells whether this execution context is running or not.
void StopExecution (void)
Terminates this execution context's execution.
void StopAllExecutions (void)
Terminates execution for all execution contexts attached to the same top execution context.
Public Member Functions inherited from Object
virtual ~Object (void)=0
Pure virtual destructor.
Additional Inherited Members
Protected Member Functions inherited from Choice
virtual void ResetToDefault (void)
Handler called when default value is required to be restored.
Protected Member Functions inherited from Line
void SetLine (const tk::String &TK_Line, const bool B_NewLine, const bool B_CleanOnTyping)
Protected line setter for child classes.
virtual void Reset (void)
Handler called when data reset is required.
Protected Member Functions inherited from UI
UI (void)
Top execution context constructor.
UI (ExecutionContext &CLI_ExecutionContext)
Child execution context constructor.
virtual const bool OnStartExecution (void)
Beginning of execution handler.
virtual const bool OnStopExecution (void)
Execution termination handler.
void EndControl (const bool B_ExecResult)
Method to call by child classes in order to end the control execution.
Protected Member Functions inherited from ExecutionContext
ExecutionContext (void)
Top context constructor.
ExecutionContext (ExecutionContext &CLI_ParentContext)
Child context constructor.
Protected Member Functions inherited from Object
Object (void)
Default constructor only available to sub-classes.
Detailed Description
Yes/No question user interface object.
Definition at line 43 of file ui_yesno.h.
Constructor & Destructor Documentation
YesNo() [1/2]
YesNo::YesNo (const bool B_DefaultAnswer) explicit
Top execution context constructor.
Parameters
B_DefaultAnswer Default answer: true for 'yes', false for 'no'.
Definition at line 58 of file ui_yesno.cpp.
References YesNo().
Referenced by YesNo().
YesNo() [2/2]
YesNo::YesNo (ExecutionContext & CLI_ParentContext, const bool B_DefaultAnswer) explicit
Child execution context constructor.
Parameters
CLI_ParentContext Parent execution context.
B_DefaultAnswer Default answer: true for 'yes', false for 'no'.
Definition at line 63 of file ui_yesno.cpp.
References YesNo().
~YesNo()
YesNo::~YesNo (void) virtual
Destructor.
Definition at line 68 of file ui_yesno.cpp.
Member Function Documentation
GetYesNo()
const bool YesNo::GetYesNo (void) const
Yes/No answer retrieval.
Returns
true for 'yes', false for 'no'.
Definition at line 72 of file ui_yesno.cpp.
References Choice::GetChoice().
OnKey()
void YesNo::OnKey (const KEY E_KeyCode) virtual
Handler called on character input.
Parameters
E_KeyCode Input key.
Reimplemented from Choice.
Definition at line 84 of file ui_yesno.cpp.
References Choice::OnKey().
The documentation for this class was generated from the following files:
ui_yesno.h
ui_yesno.cpp