CLI: Line Class Reference
Line Class Reference
Simple line user interface object.
#include <ui_line.h>
Public Member Functions
Line (const tk::String &TK_DefaultLine, const int I_MinLineLength, const int I_MaxLineLength)
Top execution context constructor.
Line (ExecutionContext &CLI_ParentContext, const tk::String &TK_DefaultLine, const int I_MinLineLength, const int I_MaxLineLength)
Child execution context constructor.
virtual ~Line (void)
Destructor.
const tk::String GetLine (void) const
Line retrieval.
virtual void OnKey (const KEY E_KeyCode)
Handler called on character input.
Public Member Functions inherited from UI
virtual ~UI (void)
Destructor.
const bool GetbExecResult (void) const
Execution result accessor.
Public Member Functions inherited from ExecutionContext
virtual ~ExecutionContext (void)
Destructor.
ExecutionContextManager & GetContextManager (void)
Execution context manager accessor.
const IODevice & GetInput (void) const
Input stream accessor.
const OutputDevice & GetStream (const STREAM_TYPE E_StreamType) const
Output stream accessor.
const bool SetStream (const STREAM_TYPE E_StreamType, OutputDevice &CLI_Stream)
Output stream positionning.
const bool StreamEnabled (const STREAM_TYPE E_StreamType) const
Enabled/disabled stream accessor.
const bool EnableStream (const STREAM_TYPE E_StreamType, const bool B_Enable)
Enable/disable stream.
void SetLang (const ResourceString::LANG E_Lang)
Language setting.
const ResourceString::LANG GetLang (void) const
Language access.
void SetBeep (const bool B_Enable)
Beep configuration setting.
const bool GetBeep (void) const
Beep configuration access.
void Beep (void)
Sends a beep signal.
void Run (IODevice &CLI_IODevice)
Runs the execution context onto the corresponding input/output device.
void Run (void)
Runs the execution context as a child context of the parent given by the construction.
const bool IsRunning (void) const
Tells whether this execution context is running or not.
void StopExecution (void)
Terminates this execution context's execution.
void StopAllExecutions (void)
Terminates execution for all execution contexts attached to the same top execution context.
Public Member Functions inherited from Object
virtual ~Object (void)=0
Pure virtual destructor.
Protected Member Functions
void SetLine (const tk::String &TK_Line, const bool B_NewLine, const bool B_CleanOnTyping)
Protected line setter for child classes.
virtual void Reset (void)
Handler called when data reset is required.
virtual void ResetToDefault (void)
Handler called when default value is required to be restored.
Protected Member Functions inherited from UI
UI (void)
Top execution context constructor.
UI (ExecutionContext &CLI_ExecutionContext)
Child execution context constructor.
virtual const bool OnStartExecution (void)
Beginning of execution handler.
virtual const bool OnStopExecution (void)
Execution termination handler.
void EndControl (const bool B_ExecResult)
Method to call by child classes in order to end the control execution.
Protected Member Functions inherited from ExecutionContext
ExecutionContext (void)
Top context constructor.
ExecutionContext (ExecutionContext &CLI_ParentContext)
Child context constructor.
Protected Member Functions inherited from Object
Object (void)
Default constructor only available to sub-classes.
Detailed Description
Simple line user interface object.
Definition at line 47 of file ui_line.h.
Constructor & Destructor Documentation
Line() [1/2]
Line::Line (const tk::String & TK_DefaultLine, const int I_MinLineLength, const int I_MaxLineLength) explicit
Top execution context constructor.
Parameters
TK_DefaultLine Default value.
I_MinLineLength Minimum line length required. -1 if not set.
I_MaxLineLength Maximum line length required. -1 if not set.
Definition at line 39 of file ui_line.cpp.
Referenced by Line().
Line() [2/2]
Line::Line (ExecutionContext & CLI_ParentContext, const tk::String & TK_DefaultLine, const int I_MinLineLength, const int I_MaxLineLength) explicit
Child execution context constructor.
Parameters
CLI_ParentContext Parent execution context.
TK_DefaultLine Default value.
I_MinLineLength Minimum line length required. -1 if not set.
I_MaxLineLength Maximum line length required. -1 if not set.
Definition at line 46 of file ui_line.cpp.
References Line().
~Line()
Line::~Line (void) virtual
Destructor.
Definition at line 53 of file ui_line.cpp.
Member Function Documentation
GetLine()
const tk::String Line::GetLine (void) const
Line retrieval.
Returns
Line entered by the user.
Definition at line 58 of file ui_line.cpp.
References CmdLineEdition::GetLine().
Referenced by Choice::GetChoice(), Float::GetFloat(), and Int::GetInt().
OnKey()
void Line::OnKey (const KEY E_KeyCode) virtual
Handler called on character input.
Parameters
E_KeyCode Input key.
Implements ExecutionContext.
Reimplemented in Choice, Float, Int, and YesNo.
Definition at line 86 of file ui_line.cpp.
References BACKSPACE, ExecutionContext::Beep(), BREAK, CmdLineEdition::CleanAll(), CLS, DELETE, CmdLineEdition::Delete(), ECHO_STREAM, CmdLineEdition::End(), UI::EndControl(), ENTER, ESCAPE, CmdLineEdition::GetLeft(), CmdLineEdition::GetLine(), CmdLineEdition::GetRight(), ExecutionContext::GetStream(), CmdLineEdition::Home(), KEY_BEGIN, KEY_END, KEY_LEFT, KEY_RIGHT, LOGOUT, CmdLineEdition::MoveCursor(), CmdLineEdition::NextLine(), NULL_KEY, and TAB.
Referenced by Float::OnKey(), Int::OnKey(), and Choice::OnKey().
Reset()
void Line::Reset (void) protected virtual
Handler called when data reset is required.
Implements UI.
Definition at line 76 of file ui_line.cpp.
References CmdLineEdition::Reset().
ResetToDefault()
void Line::ResetToDefault (void) protected virtual
Handler called when default value is required to be restored.
Implements UI.
Reimplemented in Choice, Float, and Int.
Definition at line 81 of file ui_line.cpp.
References SetLine().
Referenced by Float::ResetToDefault(), and Int::ResetToDefault().
SetLine()
void Line::SetLine (const tk::String & TK_Line, const bool B_NewLine, const bool B_CleanOnTyping) protected
Protected line setter for child classes.
Parameters
TK_Line Line to print out in place of the current line.
B_NewLine Move to a new line.
B_CleanOnTyping true when the line should be fully cleaned, false if the line can be modified.
Definition at line 63 of file ui_line.cpp.
References CmdLineEdition::CleanAll(), ECHO_STREAM, ExecutionContext::GetStream(), CmdLineEdition::NextLine(), and CmdLineEdition::Put().
Referenced by Float::OnKey(), Int::OnKey(), Choice::OnKey(), Choice::ResetToDefault(), and ResetToDefault().
The documentation for this class was generated from the following files:
ui_line.h
ui_line.cpp