CLI: Float Class Reference
Float Class Reference
Float user interface class.
#include <ui_float.h>
Public Member Functions
Float (const double D_DefaultValue, const double D_MinValue, const double D_MaxValue)
Top execution context constructor.
Float (ExecutionContext &CLI_ParentContext, const double D_DefaultValue, const double D_MinValue, const double D_MaxValue)
Child execution context constructor.
virtual ~Float (void)
Destructor.
const double GetFloat (void) const
Float retrieval.
virtual void OnKey (const KEY E_KeyCode)
Handler called on character input.
Public Member Functions inherited from Line
Line (const tk::String &TK_DefaultLine, const int I_MinLineLength, const int I_MaxLineLength)
Top execution context constructor.
Line (ExecutionContext &CLI_ParentContext, const tk::String &TK_DefaultLine, const int I_MinLineLength, const int I_MaxLineLength)
Child execution context constructor.
virtual ~Line (void)
Destructor.
const tk::String GetLine (void) const
Line retrieval.
Public Member Functions inherited from UI
virtual ~UI (void)
Destructor.
const bool GetbExecResult (void) const
Execution result accessor.
Public Member Functions inherited from ExecutionContext
virtual ~ExecutionContext (void)
Destructor.
ExecutionContextManager & GetContextManager (void)
Execution context manager accessor.
const IODevice & GetInput (void) const
Input stream accessor.
const OutputDevice & GetStream (const STREAM_TYPE E_StreamType) const
Output stream accessor.
const bool SetStream (const STREAM_TYPE E_StreamType, OutputDevice &CLI_Stream)
Output stream positionning.
const bool StreamEnabled (const STREAM_TYPE E_StreamType) const
Enabled/disabled stream accessor.
const bool EnableStream (const STREAM_TYPE E_StreamType, const bool B_Enable)
Enable/disable stream.
void SetLang (const ResourceString::LANG E_Lang)
Language setting.
const ResourceString::LANG GetLang (void) const
Language access.
void SetBeep (const bool B_Enable)
Beep configuration setting.
const bool GetBeep (void) const
Beep configuration access.
void Beep (void)
Sends a beep signal.
void Run (IODevice &CLI_IODevice)
Runs the execution context onto the corresponding input/output device.
void Run (void)
Runs the execution context as a child context of the parent given by the construction.
const bool IsRunning (void) const
Tells whether this execution context is running or not.
void StopExecution (void)
Terminates this execution context's execution.
void StopAllExecutions (void)
Terminates execution for all execution contexts attached to the same top execution context.
Public Member Functions inherited from Object
virtual ~Object (void)=0
Pure virtual destructor.
Protected Member Functions
virtual void ResetToDefault (void)
Handler called when default value is required to be restored.
Protected Member Functions inherited from Line
void SetLine (const tk::String &TK_Line, const bool B_NewLine, const bool B_CleanOnTyping)
Protected line setter for child classes.
virtual void Reset (void)
Handler called when data reset is required.
Protected Member Functions inherited from UI
UI (void)
Top execution context constructor.
UI (ExecutionContext &CLI_ExecutionContext)
Child execution context constructor.
virtual const bool OnStartExecution (void)
Beginning of execution handler.
virtual const bool OnStopExecution (void)
Execution termination handler.
void EndControl (const bool B_ExecResult)
Method to call by child classes in order to end the control execution.
Protected Member Functions inherited from ExecutionContext
ExecutionContext (void)
Top context constructor.
ExecutionContext (ExecutionContext &CLI_ParentContext)
Child context constructor.
Protected Member Functions inherited from Object
Object (void)
Default constructor only available to sub-classes.
Detailed Description
Float user interface class.
Definition at line 43 of file ui_float.h.
Constructor & Destructor Documentation
Float() [1/2]
Float::Float (const double D_DefaultValue, const double D_MinValue, const double D_MaxValue) explicit
Top execution context constructor.
Parameters
D_DefaultValue Default value.
D_MinValue Minimum value.
D_MaxValue Maximum value.
Definition at line 54 of file ui_float.cpp.
References Float().
Referenced by Float().
Float() [2/2]
Float::Float (ExecutionContext & CLI_ParentContext, const double D_DefaultValue, const double D_MinValue, const double D_MaxValue) explicit
Child execution context constructor.
Parameters
CLI_ParentContext Parent execution context.
D_DefaultValue Default value.
D_MinValue Minimum value.
D_MaxValue Maximum value.
Definition at line 60 of file ui_float.cpp.
References Float().
~Float()
Float::~Float (void) virtual
Destructor.
Definition at line 66 of file ui_float.cpp.
Member Function Documentation
GetFloat()
const double Float::GetFloat (void) const
Float retrieval.
Returns
Float value entered by the user.
Definition at line 70 of file ui_float.cpp.
References Line::GetLine(), and ParamFloat::SetstrValue().
Referenced by OnKey().
OnKey()
void Float::OnKey (const KEY E_KeyCode) virtual
Handler called on character input.
Parameters
E_KeyCode Input key.
Reimplemented from Line.
Definition at line 86 of file ui_float.cpp.
References ExecutionContext::Beep(), UI::EndControl(), ENTER, GetFloat(), NULL_KEY, Line::OnKey(), PAGE_DOWN, PAGE_UP, and Line::SetLine().
ResetToDefault()
void Float::ResetToDefault (void) protected virtual
Handler called when default value is required to be restored.
Reimplemented from Line.
Definition at line 81 of file ui_float.cpp.
References Line::ResetToDefault().
The documentation for this class was generated from the following files:
ui_float.h
ui_float.cpp