/**
 * @file
 * @author javaclic.xsl - CLI library (Alexis Royer, alexis.royer@gmail.com)
 * @warning File auto-generated by 'javaclic.xsl'. Do not edit!
 */

// ----- Extra java (option='head') -----

// ----- Imports -----
import java.util.Iterator;
import java.util.NoSuchElementException;

// ----- Extra java (option='import') -----

public class Hello extends cli.Cli {
    // ----- Sub-menus -----

    // ----- Node members -----
    cli.Keyword m_clikeyword_say_id4482721;
        cli.Keyword m_clikeyword_hello_id4482232;
            cli.Endl m_cliendl_id4481772;

    // ----- Constructor -----
    Hello() {
        super("Hello", new cli.Help());
        this.populate();
    }

    // ----- Populate -----
    public void populate() {
        m_clikeyword_say_id4482721 = (cli.Keyword) this.addElement(new cli.Keyword("say", new cli.Help()));
            m_clikeyword_hello_id4482232 = (cli.Keyword) m_clikeyword_say_id4482721.addElement(new cli.Keyword("hello", new cli.Help()));
                m_cliendl_id4481772 = (cli.Endl) m_clikeyword_hello_id4482232.addElement(new cli.Endl(new cli.Help()));
    }

    // ----- Menu execution -----
    public boolean execute(cli.CommandLine CLI_CmdLine) {
        try {
            Iterator<cli.Element> cli_Elements = CLI_CmdLine.iterator();
            cli.Element cli_Element = null;
            this_lbl:
            {
                cli_Element = cli_Elements.next();
                m_clikeyword_say_id4482721_lbl:
                if (cli_Element == m_clikeyword_say_id4482721) {
                    cli_Element = cli_Elements.next();
                    m_clikeyword_hello_id4482232_lbl:
                    if (cli_Element == m_clikeyword_hello_id4482232) {
                        cli_Element = cli_Elements.next();
                        m_cliendl_id4481772_lbl:
                        if (cli_Element == m_cliendl_id4481772) {
                            return true;
                        }
                        return false;
                    }
                    return false;
                }
                return false;
            }
        } catch (NoSuchElementException e1) {
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }


    public void onExit() {
    }

}
// ----- Extra java (option='tail') -----

